Null safety
MattHamburger/clean_framework pull request #25
Opened 2021-02-17 15:26 UTC by sarbagyastha

2021-02-17 15:36 UTC, sarbagyastha commented on lib/src/bloc/pipes.dart
> +  EventPipe({VoidCallback? onListen})
Shall I remove the `onListen` callback?

2021-02-17 15:54 UTC, texocoyotl requested changes
Minor requests, please

2021-02-17 15:54 UTC, texocoyotl commented on lib/src/locator.dart
> +  static Locator? instance;
Isn't it better to use "later" here instead of a nullable type?

2021-02-17 15:54 UTC, texocoyotl commented on lib/src/tests/view_model_pipe_tester.dart
> +    for (final item in items) {
Are you sure this is synchronous? See comment

2021-02-17 15:54 UTC, texocoyotl commented on lib/src/ui/presenter.dart
> +          return buildScreen(context, bloc, snapshot.data!);
If the model is null, we should be not calling buildScreen. Please add code so we build the error screen instead

2021-02-17 15:54 UTC, texocoyotl commented on lib/src/bloc/bloc_provider.dart
> +      create: (_) => _bloc!,
The bloc instance should not be null at this point. Please make it so it is invalid to have a BlocProvider where the builder of the bloc returns null.

2021-02-17 15:54 UTC, texocoyotl commented on lib/src/bloc/pipes.dart
> +  Stream<void> get receive {
I like this exception, good call.

2021-02-17 15:57 UTC, texocoyotl commented on lib/src/bloc/pipes.dart
> +  EventPipe({VoidCallback? onListen})
Yeah, also remove the commented line. I think this was part of an initial implementation that didn't work, I forgot it was there, ty.

2021-02-18 05:25 UTC, sarbagyastha commented on lib/src/tests/view_model_pipe_tester.dart
> +    for (final item in items) {
Yes it's synchronous. `forEach` behaves so because the **await** we use, will be inside closure, and there is no way to await the closure. 

Although there's a `Future.forEach` alternative, that provides a way to await the closure, but I prefer simple for-in loop more. What do you suggest?

2021-02-18 05:32 UTC, sarbagyastha commented on lib/src/locator.dart
> +  static Locator? instance;
If we make the field late, we won't be able to determine whether or not the field was initialized.
As we'll need to check if there's already a previous instance before creating new one, in order to create lazy singleton.

I could only come up with the following approach.

**locator.dart**
```dart
class Locator {
  static Locator? _instance;

  static init(Locator locator) => _instance ??= locator;

  static T getInstance<T extends Locator>() {
    assert(_instance != null, "$T hasn't been initialized.");
    return _instance as T;
  }

  static void dispose() => _instance = null;

  Locator._();

  factory Locator() => _instance ??= Locator._();

  Logger logger = ConsoleLogger();

  Connectivity connectivity = AlwaysOnlineConnectivity();
}
```

**lexample_locator.dart**
```dart
class ExampleLocator implements Locator {
  ExampleLocator._();

  factory ExampleLocator() {
    Locator.init(ExampleLocator._());
    return Locator.getInstance();
  }

  @override
  Connectivity connectivity = AlwaysOnlineConnectivity();

  @override
  Logger logger = ConsoleLogger(LogLevel.nothing);
  SimpleRestApi api = SimpleRestApi();

  Repository repository = Repository();

  void dispose() => Locator.dispose();
}
```

2021-02-18 05:35 UTC, sarbagyastha commented on lib/src/ui/presenter.dart
> +          return buildScreen(context, bloc, snapshot.data!);
Since we're checking for `snapshot.hasData`, the **else if** block will never have null model. That's why I am using the **bang operator (!)**.

2021-02-18 05:37 UTC, sarbagyastha commented on lib/src/bloc/bloc_provider.dart
> +      create: (_) => _bloc!,
Ya, at this point bloc is never null, that's why added a bang operator.

2021-02-18 05:38 UTC, sarbagyastha commented on lib/src/bloc/pipes.dart
> +  EventPipe({VoidCallback? onListen})
Done.

2021-02-18 21:55 UTC, texocoyotl commented on lib/src/locator.dart
> +  static Locator? instance;
I get what you are saying, being it nullable works for a simple singleton. Lets keep this for now.

2021-02-18 21:57 UTC, texocoyotl commented on lib/src/tests/view_model_pipe_tester.dart
> +    for (final item in items) {
When I was using for each in tests, I had issues because of synchronicity. We will have to confirm later if the tests that we have work fine.

2021-02-18 21:57 UTC, texocoyotl commented on lib/src/ui/presenter.dart
> +          return buildScreen(context, bloc, snapshot.data!);
You are right, was only looking at one line haha.

2021-02-18 21:58 UTC, merged